### ISSUE TITLE
Add typescript/webpack configuration to readme

### ISSUE THREAD

**Issue by anne-nelson** [avanslaars/cypress-axe#10]
I am creating a new issue for #7 as the original owner closed it despite the issue not being resolved. If you are having issues getting cypress-axe to work with Typescript/Webpack, please look at that issue for solutions.

**Comment by NicholasBoll** [comment]
I ran into this issue. After digging into it, I have no idea why `eval` is used in the original script. This is my workaround:

`support/commands.ts`
```
import * as axe from 'axe-core';

declare global {
  interface Window {
    axe: typeof axe
  }
}

Cypress.Commands.add('injectAxe', () => {
  cy.window({ log: false }).then(window => {
    window.axe = axe;
  })
})
```

This will simply assign the value returned by the import rather than running `eval` on the source (which is already done by the import...)

I'll open a PR to this repo since this should work for both browserify and webpack.
